# Generated by Django 3.2.19 on 2023-05-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='message',
            new_name='written_review',
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.IntegerField(choices=[(0, 'Kitchen, Oishii Ramen'), (1, 'Workshop Room, Oishii Ramen')]),
        ),
    ]
