# Generated by Django 3.2.19 on 2023-05-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='location',
        ),
    ]
