# Generated by Django 3.2.19 on 2023-05-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_timetable_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='location',
        ),
    ]
