# Generated by Django 3.2.19 on 2023-05-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_course_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='ends',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
