# Generated by Django 3.2.19 on 2023-05-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20230516_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='duration',
            new_name='duration_in_hrs',
        ),
    ]
