# Generated by Django 3.2.19 on 2023-05-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rename_price_course_price_in_gbp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='username',
            new_name='user',
        ),
    ]
