# Generated by Django 3.2.19 on 2023-05-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_timetable_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price_in_gbp',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
